export enum MESSAGE_TYPES {
  GET_CONFIG = 'GET_CONFIG',
  CONFIG_UPDATED = 'CONFIG_UPDATED',
  UPDATE_CONFIG = 'UPDATE_CONFIG',
  CONTENT_LOADED = 'CONTENT_LOADED',
  GET_URL = 'GET_URL',
  GET_ANALYSIS_RES = 'GET_ANALYSIS_RES',
}
